//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AISCM.Droid.net.azurewebsites.agc20171 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AISCMSoap", Namespace="http://tempuri.org/")]
    public partial class AISCM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback get_marketsOperationCompleted;
        
        private System.Threading.SendOrPostCallback sell_to_marketOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_market_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getlatlngOperationCompleted;
        
        private System.Threading.SendOrPostCallback signinOperationCompleted;
        
        private System.Threading.SendOrPostCallback update_gcm_tokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_tokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback signupOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_farmer_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_manufacturing_company_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback update_farm_phOperationCompleted;
        
        private System.Threading.SendOrPostCallback adduserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSoilIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback predict_cropsOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_water_statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_current_farm_statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_current_cropsOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_appx_productionOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_new_crop_farmerOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_current_bidsOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_bidsOperationCompleted;
        
        private System.Threading.SendOrPostCallback accept_bidOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_bid_details_mucpOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_bid_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_bids_farmerOperationCompleted;
        
        private System.Threading.SendOrPostCallback set_new_bidOperationCompleted;
        
        private System.Threading.SendOrPostCallback update_farm_statusOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_notificaton_generalizedOperationCompleted;
        
        private System.Threading.SendOrPostCallback send_notificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getdatetimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AISCM() {
            this.Url = "http://agc2017.azurewebsites.net/AISCM.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event get_marketsCompletedEventHandler get_marketsCompleted;
        
        /// <remarks/>
        public event sell_to_marketCompletedEventHandler sell_to_marketCompleted;
        
        /// <remarks/>
        public event get_market_detailsCompletedEventHandler get_market_detailsCompleted;
        
        /// <remarks/>
        public event getlatlngCompletedEventHandler getlatlngCompleted;
        
        /// <remarks/>
        public event signinCompletedEventHandler signinCompleted;
        
        /// <remarks/>
        public event update_gcm_tokenCompletedEventHandler update_gcm_tokenCompleted;
        
        /// <remarks/>
        public event add_tokenCompletedEventHandler add_tokenCompleted;
        
        /// <remarks/>
        public event signupCompletedEventHandler signupCompleted;
        
        /// <remarks/>
        public event add_farmer_detailsCompletedEventHandler add_farmer_detailsCompleted;
        
        /// <remarks/>
        public event add_manufacturing_company_detailsCompletedEventHandler add_manufacturing_company_detailsCompleted;
        
        /// <remarks/>
        public event update_farm_phCompletedEventHandler update_farm_phCompleted;
        
        /// <remarks/>
        public event adduserCompletedEventHandler adduserCompleted;
        
        /// <remarks/>
        public event getSoilIdCompletedEventHandler getSoilIdCompleted;
        
        /// <remarks/>
        public event predict_cropsCompletedEventHandler predict_cropsCompleted;
        
        /// <remarks/>
        public event get_water_statusCompletedEventHandler get_water_statusCompleted;
        
        /// <remarks/>
        public event get_current_farm_statusCompletedEventHandler get_current_farm_statusCompleted;
        
        /// <remarks/>
        public event get_current_cropsCompletedEventHandler get_current_cropsCompleted;
        
        /// <remarks/>
        public event add_appx_productionCompletedEventHandler add_appx_productionCompleted;
        
        /// <remarks/>
        public event add_new_crop_farmerCompletedEventHandler add_new_crop_farmerCompleted;
        
        /// <remarks/>
        public event get_current_bidsCompletedEventHandler get_current_bidsCompleted;
        
        /// <remarks/>
        public event get_bidsCompletedEventHandler get_bidsCompleted;
        
        /// <remarks/>
        public event accept_bidCompletedEventHandler accept_bidCompleted;
        
        /// <remarks/>
        public event get_bid_details_mucpCompletedEventHandler get_bid_details_mucpCompleted;
        
        /// <remarks/>
        public event get_bid_detailsCompletedEventHandler get_bid_detailsCompleted;
        
        /// <remarks/>
        public event get_bids_farmerCompletedEventHandler get_bids_farmerCompleted;
        
        /// <remarks/>
        public event set_new_bidCompletedEventHandler set_new_bidCompleted;
        
        /// <remarks/>
        public event update_farm_statusCompletedEventHandler update_farm_statusCompleted;
        
        /// <remarks/>
        public event send_notificaton_generalizedCompletedEventHandler send_notificaton_generalizedCompleted;
        
        /// <remarks/>
        public event send_notificationCompletedEventHandler send_notificationCompleted;
        
        /// <remarks/>
        public event getdatetimeCompletedEventHandler getdatetimeCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_markets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_markets(string cropid) {
            object[] results = this.Invoke("get_markets", new object[] {
                        cropid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_marketsAsync(string cropid) {
            this.get_marketsAsync(cropid, null);
        }
        
        /// <remarks/>
        public void get_marketsAsync(string cropid, object userState) {
            if ((this.get_marketsOperationCompleted == null)) {
                this.get_marketsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_marketsOperationCompleted);
            }
            this.InvokeAsync("get_markets", new object[] {
                        cropid}, this.get_marketsOperationCompleted, userState);
        }
        
        private void Onget_marketsOperationCompleted(object arg) {
            if ((this.get_marketsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_marketsCompleted(this, new get_marketsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sell_to_market", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void sell_to_market(string email, string cropid) {
            this.Invoke("sell_to_market", new object[] {
                        email,
                        cropid});
        }
        
        /// <remarks/>
        public void sell_to_marketAsync(string email, string cropid) {
            this.sell_to_marketAsync(email, cropid, null);
        }
        
        /// <remarks/>
        public void sell_to_marketAsync(string email, string cropid, object userState) {
            if ((this.sell_to_marketOperationCompleted == null)) {
                this.sell_to_marketOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsell_to_marketOperationCompleted);
            }
            this.InvokeAsync("sell_to_market", new object[] {
                        email,
                        cropid}, this.sell_to_marketOperationCompleted, userState);
        }
        
        private void Onsell_to_marketOperationCompleted(object arg) {
            if ((this.sell_to_marketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sell_to_marketCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_market_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_market_details(string email, string marketid, string cropid) {
            object[] results = this.Invoke("get_market_details", new object[] {
                        email,
                        marketid,
                        cropid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_market_detailsAsync(string email, string marketid, string cropid) {
            this.get_market_detailsAsync(email, marketid, cropid, null);
        }
        
        /// <remarks/>
        public void get_market_detailsAsync(string email, string marketid, string cropid, object userState) {
            if ((this.get_market_detailsOperationCompleted == null)) {
                this.get_market_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_market_detailsOperationCompleted);
            }
            this.InvokeAsync("get_market_details", new object[] {
                        email,
                        marketid,
                        cropid}, this.get_market_detailsOperationCompleted, userState);
        }
        
        private void Onget_market_detailsOperationCompleted(object arg) {
            if ((this.get_market_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_market_detailsCompleted(this, new get_market_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getlatlng", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getlatlng(string address) {
            object[] results = this.Invoke("getlatlng", new object[] {
                        address});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getlatlngAsync(string address) {
            this.getlatlngAsync(address, null);
        }
        
        /// <remarks/>
        public void getlatlngAsync(string address, object userState) {
            if ((this.getlatlngOperationCompleted == null)) {
                this.getlatlngOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetlatlngOperationCompleted);
            }
            this.InvokeAsync("getlatlng", new object[] {
                        address}, this.getlatlngOperationCompleted, userState);
        }
        
        private void OngetlatlngOperationCompleted(object arg) {
            if ((this.getlatlngCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getlatlngCompleted(this, new getlatlngCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/signin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int signin(string email) {
            object[] results = this.Invoke("signin", new object[] {
                        email});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void signinAsync(string email) {
            this.signinAsync(email, null);
        }
        
        /// <remarks/>
        public void signinAsync(string email, object userState) {
            if ((this.signinOperationCompleted == null)) {
                this.signinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsigninOperationCompleted);
            }
            this.InvokeAsync("signin", new object[] {
                        email}, this.signinOperationCompleted, userState);
        }
        
        private void OnsigninOperationCompleted(object arg) {
            if ((this.signinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.signinCompleted(this, new signinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_gcm_token", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update_gcm_token(string email, string token) {
            this.Invoke("update_gcm_token", new object[] {
                        email,
                        token});
        }
        
        /// <remarks/>
        public void update_gcm_tokenAsync(string email, string token) {
            this.update_gcm_tokenAsync(email, token, null);
        }
        
        /// <remarks/>
        public void update_gcm_tokenAsync(string email, string token, object userState) {
            if ((this.update_gcm_tokenOperationCompleted == null)) {
                this.update_gcm_tokenOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdate_gcm_tokenOperationCompleted);
            }
            this.InvokeAsync("update_gcm_token", new object[] {
                        email,
                        token}, this.update_gcm_tokenOperationCompleted, userState);
        }
        
        private void Onupdate_gcm_tokenOperationCompleted(object arg) {
            if ((this.update_gcm_tokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.update_gcm_tokenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_token", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void add_token(string email, string token) {
            this.Invoke("add_token", new object[] {
                        email,
                        token});
        }
        
        /// <remarks/>
        public void add_tokenAsync(string email, string token) {
            this.add_tokenAsync(email, token, null);
        }
        
        /// <remarks/>
        public void add_tokenAsync(string email, string token, object userState) {
            if ((this.add_tokenOperationCompleted == null)) {
                this.add_tokenOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_tokenOperationCompleted);
            }
            this.InvokeAsync("add_token", new object[] {
                        email,
                        token}, this.add_tokenOperationCompleted, userState);
        }
        
        private void Onadd_tokenOperationCompleted(object arg) {
            if ((this.add_tokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_tokenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/signup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int signup(string email, string name, string gender, string ut) {
            object[] results = this.Invoke("signup", new object[] {
                        email,
                        name,
                        gender,
                        ut});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void signupAsync(string email, string name, string gender, string ut) {
            this.signupAsync(email, name, gender, ut, null);
        }
        
        /// <remarks/>
        public void signupAsync(string email, string name, string gender, string ut, object userState) {
            if ((this.signupOperationCompleted == null)) {
                this.signupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsignupOperationCompleted);
            }
            this.InvokeAsync("signup", new object[] {
                        email,
                        name,
                        gender,
                        ut}, this.signupOperationCompleted, userState);
        }
        
        private void OnsignupOperationCompleted(object arg) {
            if ((this.signupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.signupCompleted(this, new signupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_farmer_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void add_farmer_details(string email, string address, string cnum, string ph, string region, string wth, string raspberry_id) {
            this.Invoke("add_farmer_details", new object[] {
                        email,
                        address,
                        cnum,
                        ph,
                        region,
                        wth,
                        raspberry_id});
        }
        
        /// <remarks/>
        public void add_farmer_detailsAsync(string email, string address, string cnum, string ph, string region, string wth, string raspberry_id) {
            this.add_farmer_detailsAsync(email, address, cnum, ph, region, wth, raspberry_id, null);
        }
        
        /// <remarks/>
        public void add_farmer_detailsAsync(string email, string address, string cnum, string ph, string region, string wth, string raspberry_id, object userState) {
            if ((this.add_farmer_detailsOperationCompleted == null)) {
                this.add_farmer_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_farmer_detailsOperationCompleted);
            }
            this.InvokeAsync("add_farmer_details", new object[] {
                        email,
                        address,
                        cnum,
                        ph,
                        region,
                        wth,
                        raspberry_id}, this.add_farmer_detailsOperationCompleted, userState);
        }
        
        private void Onadd_farmer_detailsOperationCompleted(object arg) {
            if ((this.add_farmer_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_farmer_detailsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_manufacturing_company_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void add_manufacturing_company_details(string email, string address, string cnum, string name, string region) {
            this.Invoke("add_manufacturing_company_details", new object[] {
                        email,
                        address,
                        cnum,
                        name,
                        region});
        }
        
        /// <remarks/>
        public void add_manufacturing_company_detailsAsync(string email, string address, string cnum, string name, string region) {
            this.add_manufacturing_company_detailsAsync(email, address, cnum, name, region, null);
        }
        
        /// <remarks/>
        public void add_manufacturing_company_detailsAsync(string email, string address, string cnum, string name, string region, object userState) {
            if ((this.add_manufacturing_company_detailsOperationCompleted == null)) {
                this.add_manufacturing_company_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_manufacturing_company_detailsOperationCompleted);
            }
            this.InvokeAsync("add_manufacturing_company_details", new object[] {
                        email,
                        address,
                        cnum,
                        name,
                        region}, this.add_manufacturing_company_detailsOperationCompleted, userState);
        }
        
        private void Onadd_manufacturing_company_detailsOperationCompleted(object arg) {
            if ((this.add_manufacturing_company_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_manufacturing_company_detailsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_farm_ph", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string update_farm_ph(string email, string ph) {
            object[] results = this.Invoke("update_farm_ph", new object[] {
                        email,
                        ph});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void update_farm_phAsync(string email, string ph) {
            this.update_farm_phAsync(email, ph, null);
        }
        
        /// <remarks/>
        public void update_farm_phAsync(string email, string ph, object userState) {
            if ((this.update_farm_phOperationCompleted == null)) {
                this.update_farm_phOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdate_farm_phOperationCompleted);
            }
            this.InvokeAsync("update_farm_ph", new object[] {
                        email,
                        ph}, this.update_farm_phOperationCompleted, userState);
        }
        
        private void Onupdate_farm_phOperationCompleted(object arg) {
            if ((this.update_farm_phCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.update_farm_phCompleted(this, new update_farm_phCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/adduser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string adduser(string email, string user_type, string raspberry_id) {
            object[] results = this.Invoke("adduser", new object[] {
                        email,
                        user_type,
                        raspberry_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void adduserAsync(string email, string user_type, string raspberry_id) {
            this.adduserAsync(email, user_type, raspberry_id, null);
        }
        
        /// <remarks/>
        public void adduserAsync(string email, string user_type, string raspberry_id, object userState) {
            if ((this.adduserOperationCompleted == null)) {
                this.adduserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnadduserOperationCompleted);
            }
            this.InvokeAsync("adduser", new object[] {
                        email,
                        user_type,
                        raspberry_id}, this.adduserOperationCompleted, userState);
        }
        
        private void OnadduserOperationCompleted(object arg) {
            if ((this.adduserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adduserCompleted(this, new adduserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSoilId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSoilId(string p, string disid) {
            object[] results = this.Invoke("getSoilId", new object[] {
                        p,
                        disid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSoilIdAsync(string p, string disid) {
            this.getSoilIdAsync(p, disid, null);
        }
        
        /// <remarks/>
        public void getSoilIdAsync(string p, string disid, object userState) {
            if ((this.getSoilIdOperationCompleted == null)) {
                this.getSoilIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSoilIdOperationCompleted);
            }
            this.InvokeAsync("getSoilId", new object[] {
                        p,
                        disid}, this.getSoilIdOperationCompleted, userState);
        }
        
        private void OngetSoilIdOperationCompleted(object arg) {
            if ((this.getSoilIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSoilIdCompleted(this, new getSoilIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/predict_crops", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] predict_crops(string email) {
            object[] results = this.Invoke("predict_crops", new object[] {
                        email});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void predict_cropsAsync(string email) {
            this.predict_cropsAsync(email, null);
        }
        
        /// <remarks/>
        public void predict_cropsAsync(string email, object userState) {
            if ((this.predict_cropsOperationCompleted == null)) {
                this.predict_cropsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpredict_cropsOperationCompleted);
            }
            this.InvokeAsync("predict_crops", new object[] {
                        email}, this.predict_cropsOperationCompleted, userState);
        }
        
        private void Onpredict_cropsOperationCompleted(object arg) {
            if ((this.predict_cropsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.predict_cropsCompleted(this, new predict_cropsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_water_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string get_water_status(string email) {
            object[] results = this.Invoke("get_water_status", new object[] {
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void get_water_statusAsync(string email) {
            this.get_water_statusAsync(email, null);
        }
        
        /// <remarks/>
        public void get_water_statusAsync(string email, object userState) {
            if ((this.get_water_statusOperationCompleted == null)) {
                this.get_water_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_water_statusOperationCompleted);
            }
            this.InvokeAsync("get_water_status", new object[] {
                        email}, this.get_water_statusOperationCompleted, userState);
        }
        
        private void Onget_water_statusOperationCompleted(object arg) {
            if ((this.get_water_statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_water_statusCompleted(this, new get_water_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_current_farm_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_current_farm_status(string email) {
            object[] results = this.Invoke("get_current_farm_status", new object[] {
                        email});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_current_farm_statusAsync(string email) {
            this.get_current_farm_statusAsync(email, null);
        }
        
        /// <remarks/>
        public void get_current_farm_statusAsync(string email, object userState) {
            if ((this.get_current_farm_statusOperationCompleted == null)) {
                this.get_current_farm_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_current_farm_statusOperationCompleted);
            }
            this.InvokeAsync("get_current_farm_status", new object[] {
                        email}, this.get_current_farm_statusOperationCompleted, userState);
        }
        
        private void Onget_current_farm_statusOperationCompleted(object arg) {
            if ((this.get_current_farm_statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_current_farm_statusCompleted(this, new get_current_farm_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_current_crops", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_current_crops(string email) {
            object[] results = this.Invoke("get_current_crops", new object[] {
                        email});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_current_cropsAsync(string email) {
            this.get_current_cropsAsync(email, null);
        }
        
        /// <remarks/>
        public void get_current_cropsAsync(string email, object userState) {
            if ((this.get_current_cropsOperationCompleted == null)) {
                this.get_current_cropsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_current_cropsOperationCompleted);
            }
            this.InvokeAsync("get_current_crops", new object[] {
                        email}, this.get_current_cropsOperationCompleted, userState);
        }
        
        private void Onget_current_cropsOperationCompleted(object arg) {
            if ((this.get_current_cropsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_current_cropsCompleted(this, new get_current_cropsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_appx_production", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void add_appx_production(string email, string cropid, string appx_prod) {
            this.Invoke("add_appx_production", new object[] {
                        email,
                        cropid,
                        appx_prod});
        }
        
        /// <remarks/>
        public void add_appx_productionAsync(string email, string cropid, string appx_prod) {
            this.add_appx_productionAsync(email, cropid, appx_prod, null);
        }
        
        /// <remarks/>
        public void add_appx_productionAsync(string email, string cropid, string appx_prod, object userState) {
            if ((this.add_appx_productionOperationCompleted == null)) {
                this.add_appx_productionOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_appx_productionOperationCompleted);
            }
            this.InvokeAsync("add_appx_production", new object[] {
                        email,
                        cropid,
                        appx_prod}, this.add_appx_productionOperationCompleted, userState);
        }
        
        private void Onadd_appx_productionOperationCompleted(object arg) {
            if ((this.add_appx_productionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_appx_productionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_new_crop_farmer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string add_new_crop_farmer(string email, string cropid, string app_prod) {
            object[] results = this.Invoke("add_new_crop_farmer", new object[] {
                        email,
                        cropid,
                        app_prod});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void add_new_crop_farmerAsync(string email, string cropid, string app_prod) {
            this.add_new_crop_farmerAsync(email, cropid, app_prod, null);
        }
        
        /// <remarks/>
        public void add_new_crop_farmerAsync(string email, string cropid, string app_prod, object userState) {
            if ((this.add_new_crop_farmerOperationCompleted == null)) {
                this.add_new_crop_farmerOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_new_crop_farmerOperationCompleted);
            }
            this.InvokeAsync("add_new_crop_farmer", new object[] {
                        email,
                        cropid,
                        app_prod}, this.add_new_crop_farmerOperationCompleted, userState);
        }
        
        private void Onadd_new_crop_farmerOperationCompleted(object arg) {
            if ((this.add_new_crop_farmerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_new_crop_farmerCompleted(this, new add_new_crop_farmerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_current_bids", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_current_bids(string email) {
            object[] results = this.Invoke("get_current_bids", new object[] {
                        email});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_current_bidsAsync(string email) {
            this.get_current_bidsAsync(email, null);
        }
        
        /// <remarks/>
        public void get_current_bidsAsync(string email, object userState) {
            if ((this.get_current_bidsOperationCompleted == null)) {
                this.get_current_bidsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_current_bidsOperationCompleted);
            }
            this.InvokeAsync("get_current_bids", new object[] {
                        email}, this.get_current_bidsOperationCompleted, userState);
        }
        
        private void Onget_current_bidsOperationCompleted(object arg) {
            if ((this.get_current_bidsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_current_bidsCompleted(this, new get_current_bidsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_bids", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_bids(string email) {
            object[] results = this.Invoke("get_bids", new object[] {
                        email});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_bidsAsync(string email) {
            this.get_bidsAsync(email, null);
        }
        
        /// <remarks/>
        public void get_bidsAsync(string email, object userState) {
            if ((this.get_bidsOperationCompleted == null)) {
                this.get_bidsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_bidsOperationCompleted);
            }
            this.InvokeAsync("get_bids", new object[] {
                        email}, this.get_bidsOperationCompleted, userState);
        }
        
        private void Onget_bidsOperationCompleted(object arg) {
            if ((this.get_bidsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_bidsCompleted(this, new get_bidsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/accept_bid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string accept_bid(string email, string bidid) {
            object[] results = this.Invoke("accept_bid", new object[] {
                        email,
                        bidid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void accept_bidAsync(string email, string bidid) {
            this.accept_bidAsync(email, bidid, null);
        }
        
        /// <remarks/>
        public void accept_bidAsync(string email, string bidid, object userState) {
            if ((this.accept_bidOperationCompleted == null)) {
                this.accept_bidOperationCompleted = new System.Threading.SendOrPostCallback(this.Onaccept_bidOperationCompleted);
            }
            this.InvokeAsync("accept_bid", new object[] {
                        email,
                        bidid}, this.accept_bidOperationCompleted, userState);
        }
        
        private void Onaccept_bidOperationCompleted(object arg) {
            if ((this.accept_bidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.accept_bidCompleted(this, new accept_bidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_bid_details_mucp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_bid_details_mucp(string bidid) {
            object[] results = this.Invoke("get_bid_details_mucp", new object[] {
                        bidid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_bid_details_mucpAsync(string bidid) {
            this.get_bid_details_mucpAsync(bidid, null);
        }
        
        /// <remarks/>
        public void get_bid_details_mucpAsync(string bidid, object userState) {
            if ((this.get_bid_details_mucpOperationCompleted == null)) {
                this.get_bid_details_mucpOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_bid_details_mucpOperationCompleted);
            }
            this.InvokeAsync("get_bid_details_mucp", new object[] {
                        bidid}, this.get_bid_details_mucpOperationCompleted, userState);
        }
        
        private void Onget_bid_details_mucpOperationCompleted(object arg) {
            if ((this.get_bid_details_mucpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_bid_details_mucpCompleted(this, new get_bid_details_mucpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_bid_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_bid_details(string bidid) {
            object[] results = this.Invoke("get_bid_details", new object[] {
                        bidid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_bid_detailsAsync(string bidid) {
            this.get_bid_detailsAsync(bidid, null);
        }
        
        /// <remarks/>
        public void get_bid_detailsAsync(string bidid, object userState) {
            if ((this.get_bid_detailsOperationCompleted == null)) {
                this.get_bid_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_bid_detailsOperationCompleted);
            }
            this.InvokeAsync("get_bid_details", new object[] {
                        bidid}, this.get_bid_detailsOperationCompleted, userState);
        }
        
        private void Onget_bid_detailsOperationCompleted(object arg) {
            if ((this.get_bid_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_bid_detailsCompleted(this, new get_bid_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_bids_farmer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] get_bids_farmer(string email) {
            object[] results = this.Invoke("get_bids_farmer", new object[] {
                        email});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void get_bids_farmerAsync(string email) {
            this.get_bids_farmerAsync(email, null);
        }
        
        /// <remarks/>
        public void get_bids_farmerAsync(string email, object userState) {
            if ((this.get_bids_farmerOperationCompleted == null)) {
                this.get_bids_farmerOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_bids_farmerOperationCompleted);
            }
            this.InvokeAsync("get_bids_farmer", new object[] {
                        email}, this.get_bids_farmerOperationCompleted, userState);
        }
        
        private void Onget_bids_farmerOperationCompleted(object arg) {
            if ((this.get_bids_farmerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_bids_farmerCompleted(this, new get_bids_farmerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/set_new_bid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string set_new_bid(string email, string cropid, string appx_prod, string rate_per_qtl) {
            object[] results = this.Invoke("set_new_bid", new object[] {
                        email,
                        cropid,
                        appx_prod,
                        rate_per_qtl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void set_new_bidAsync(string email, string cropid, string appx_prod, string rate_per_qtl) {
            this.set_new_bidAsync(email, cropid, appx_prod, rate_per_qtl, null);
        }
        
        /// <remarks/>
        public void set_new_bidAsync(string email, string cropid, string appx_prod, string rate_per_qtl, object userState) {
            if ((this.set_new_bidOperationCompleted == null)) {
                this.set_new_bidOperationCompleted = new System.Threading.SendOrPostCallback(this.Onset_new_bidOperationCompleted);
            }
            this.InvokeAsync("set_new_bid", new object[] {
                        email,
                        cropid,
                        appx_prod,
                        rate_per_qtl}, this.set_new_bidOperationCompleted, userState);
        }
        
        private void Onset_new_bidOperationCompleted(object arg) {
            if ((this.set_new_bidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.set_new_bidCompleted(this, new set_new_bidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_farm_status", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string update_farm_status(string temp, string mois, string raspberry_id, string water_tank_level, string water_pump_status) {
            object[] results = this.Invoke("update_farm_status", new object[] {
                        temp,
                        mois,
                        raspberry_id,
                        water_tank_level,
                        water_pump_status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void update_farm_statusAsync(string temp, string mois, string raspberry_id, string water_tank_level, string water_pump_status) {
            this.update_farm_statusAsync(temp, mois, raspberry_id, water_tank_level, water_pump_status, null);
        }
        
        /// <remarks/>
        public void update_farm_statusAsync(string temp, string mois, string raspberry_id, string water_tank_level, string water_pump_status, object userState) {
            if ((this.update_farm_statusOperationCompleted == null)) {
                this.update_farm_statusOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdate_farm_statusOperationCompleted);
            }
            this.InvokeAsync("update_farm_status", new object[] {
                        temp,
                        mois,
                        raspberry_id,
                        water_tank_level,
                        water_pump_status}, this.update_farm_statusOperationCompleted, userState);
        }
        
        private void Onupdate_farm_statusOperationCompleted(object arg) {
            if ((this.update_farm_statusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.update_farm_statusCompleted(this, new update_farm_statusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_notificaton_generalized", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void send_notificaton_generalized(string email, string msg) {
            this.Invoke("send_notificaton_generalized", new object[] {
                        email,
                        msg});
        }
        
        /// <remarks/>
        public void send_notificaton_generalizedAsync(string email, string msg) {
            this.send_notificaton_generalizedAsync(email, msg, null);
        }
        
        /// <remarks/>
        public void send_notificaton_generalizedAsync(string email, string msg, object userState) {
            if ((this.send_notificaton_generalizedOperationCompleted == null)) {
                this.send_notificaton_generalizedOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_notificaton_generalizedOperationCompleted);
            }
            this.InvokeAsync("send_notificaton_generalized", new object[] {
                        email,
                        msg}, this.send_notificaton_generalizedOperationCompleted, userState);
        }
        
        private void Onsend_notificaton_generalizedOperationCompleted(object arg) {
            if ((this.send_notificaton_generalizedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_notificaton_generalizedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/send_notification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void send_notification(string id, string st) {
            this.Invoke("send_notification", new object[] {
                        id,
                        st});
        }
        
        /// <remarks/>
        public void send_notificationAsync(string id, string st) {
            this.send_notificationAsync(id, st, null);
        }
        
        /// <remarks/>
        public void send_notificationAsync(string id, string st, object userState) {
            if ((this.send_notificationOperationCompleted == null)) {
                this.send_notificationOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsend_notificationOperationCompleted);
            }
            this.InvokeAsync("send_notification", new object[] {
                        id,
                        st}, this.send_notificationOperationCompleted, userState);
        }
        
        private void Onsend_notificationOperationCompleted(object arg) {
            if ((this.send_notificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.send_notificationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getdatetime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getdatetime() {
            object[] results = this.Invoke("getdatetime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getdatetimeAsync() {
            this.getdatetimeAsync(null);
        }
        
        /// <remarks/>
        public void getdatetimeAsync(object userState) {
            if ((this.getdatetimeOperationCompleted == null)) {
                this.getdatetimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetdatetimeOperationCompleted);
            }
            this.InvokeAsync("getdatetime", new object[0], this.getdatetimeOperationCompleted, userState);
        }
        
        private void OngetdatetimeOperationCompleted(object arg) {
            if ((this.getdatetimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getdatetimeCompleted(this, new getdatetimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_marketsCompletedEventHandler(object sender, get_marketsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_marketsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_marketsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void sell_to_marketCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_market_detailsCompletedEventHandler(object sender, get_market_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_market_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_market_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getlatlngCompletedEventHandler(object sender, getlatlngCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getlatlngCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getlatlngCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void signinCompletedEventHandler(object sender, signinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class signinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal signinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void update_gcm_tokenCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void add_tokenCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void signupCompletedEventHandler(object sender, signupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class signupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal signupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void add_farmer_detailsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void add_manufacturing_company_detailsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void update_farm_phCompletedEventHandler(object sender, update_farm_phCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class update_farm_phCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal update_farm_phCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void adduserCompletedEventHandler(object sender, adduserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class adduserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal adduserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getSoilIdCompletedEventHandler(object sender, getSoilIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSoilIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSoilIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void predict_cropsCompletedEventHandler(object sender, predict_cropsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class predict_cropsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal predict_cropsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_water_statusCompletedEventHandler(object sender, get_water_statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_water_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_water_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_current_farm_statusCompletedEventHandler(object sender, get_current_farm_statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_current_farm_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_current_farm_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_current_cropsCompletedEventHandler(object sender, get_current_cropsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_current_cropsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_current_cropsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void add_appx_productionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void add_new_crop_farmerCompletedEventHandler(object sender, add_new_crop_farmerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_new_crop_farmerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_new_crop_farmerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_current_bidsCompletedEventHandler(object sender, get_current_bidsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_current_bidsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_current_bidsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_bidsCompletedEventHandler(object sender, get_bidsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_bidsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_bidsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void accept_bidCompletedEventHandler(object sender, accept_bidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class accept_bidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal accept_bidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_bid_details_mucpCompletedEventHandler(object sender, get_bid_details_mucpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_bid_details_mucpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_bid_details_mucpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_bid_detailsCompletedEventHandler(object sender, get_bid_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_bid_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_bid_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void get_bids_farmerCompletedEventHandler(object sender, get_bids_farmerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_bids_farmerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_bids_farmerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void set_new_bidCompletedEventHandler(object sender, set_new_bidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class set_new_bidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal set_new_bidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void update_farm_statusCompletedEventHandler(object sender, update_farm_statusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class update_farm_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal update_farm_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void send_notificaton_generalizedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void send_notificationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getdatetimeCompletedEventHandler(object sender, getdatetimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getdatetimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getdatetimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591