//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AISCM.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.AISCMSoap")]
    public interface AISCMSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/signin", ReplyAction="*")]
        System.IAsyncResult Beginsignin(AISCM.ServiceReference2.signinRequest request, System.AsyncCallback callback, object asyncState);
        
        AISCM.ServiceReference2.signinResponse Endsignin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/signup", ReplyAction="*")]
        System.IAsyncResult Beginsignup(AISCM.ServiceReference2.signupRequest request, System.AsyncCallback callback, object asyncState);
        
        AISCM.ServiceReference2.signupResponse Endsignup(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/adduser", ReplyAction="*")]
        System.IAsyncResult Beginadduser(AISCM.ServiceReference2.adduserRequest request, System.AsyncCallback callback, object asyncState);
        
        AISCM.ServiceReference2.adduserResponse Endadduser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/get_current_farm_status", ReplyAction="*")]
        System.IAsyncResult Beginget_current_farm_status(AISCM.ServiceReference2.get_current_farm_statusRequest request, System.AsyncCallback callback, object asyncState);
        
        AISCM.ServiceReference2.get_current_farm_statusResponse Endget_current_farm_status(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/update_farm_status", ReplyAction="*")]
        System.IAsyncResult Beginupdate_farm_status(AISCM.ServiceReference2.update_farm_statusRequest request, System.AsyncCallback callback, object asyncState);
        
        AISCM.ServiceReference2.update_farm_statusResponse Endupdate_farm_status(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(AISCM.ServiceReference2.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        AISCM.ServiceReference2.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class signinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signin", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.signinRequestBody Body;
        
        public signinRequest() {
        }
        
        public signinRequest(AISCM.ServiceReference2.signinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public signinRequestBody() {
        }
        
        public signinRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class signinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signinResponse", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.signinResponseBody Body;
        
        public signinResponse() {
        }
        
        public signinResponse(AISCM.ServiceReference2.signinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int signinResult;
        
        public signinResponseBody() {
        }
        
        public signinResponseBody(int signinResult) {
            this.signinResult = signinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class signupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signup", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.signupRequestBody Body;
        
        public signupRequest() {
        }
        
        public signupRequest(AISCM.ServiceReference2.signupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gender;
        
        public signupRequestBody() {
        }
        
        public signupRequestBody(string email, string name, string gender) {
            this.email = email;
            this.name = name;
            this.gender = gender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class signupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signupResponse", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.signupResponseBody Body;
        
        public signupResponse() {
        }
        
        public signupResponse(AISCM.ServiceReference2.signupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int signupResult;
        
        public signupResponseBody() {
        }
        
        public signupResponseBody(int signupResult) {
            this.signupResult = signupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class adduserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adduser", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.adduserRequestBody Body;
        
        public adduserRequest() {
        }
        
        public adduserRequest(AISCM.ServiceReference2.adduserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class adduserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string raspberry_id;
        
        public adduserRequestBody() {
        }
        
        public adduserRequestBody(string email, string user_type, string raspberry_id) {
            this.email = email;
            this.user_type = user_type;
            this.raspberry_id = raspberry_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class adduserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="adduserResponse", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.adduserResponseBody Body;
        
        public adduserResponse() {
        }
        
        public adduserResponse(AISCM.ServiceReference2.adduserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class adduserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string adduserResult;
        
        public adduserResponseBody() {
        }
        
        public adduserResponseBody(string adduserResult) {
            this.adduserResult = adduserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class get_current_farm_statusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_current_farm_status", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.get_current_farm_statusRequestBody Body;
        
        public get_current_farm_statusRequest() {
        }
        
        public get_current_farm_statusRequest(AISCM.ServiceReference2.get_current_farm_statusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_current_farm_statusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public get_current_farm_statusRequestBody() {
        }
        
        public get_current_farm_statusRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class get_current_farm_statusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_current_farm_statusResponse", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.get_current_farm_statusResponseBody Body;
        
        public get_current_farm_statusResponse() {
        }
        
        public get_current_farm_statusResponse(AISCM.ServiceReference2.get_current_farm_statusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_current_farm_statusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string get_current_farm_statusResult;
        
        public get_current_farm_statusResponseBody() {
        }
        
        public get_current_farm_statusResponseBody(string get_current_farm_statusResult) {
            this.get_current_farm_statusResult = get_current_farm_statusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class update_farm_statusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update_farm_status", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.update_farm_statusRequestBody Body;
        
        public update_farm_statusRequest() {
        }
        
        public update_farm_statusRequest(AISCM.ServiceReference2.update_farm_statusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class update_farm_statusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string temp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string moisture;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string raspberry_id;
        
        public update_farm_statusRequestBody() {
        }
        
        public update_farm_statusRequestBody(string temp, string moisture, string raspberry_id) {
            this.temp = temp;
            this.moisture = moisture;
            this.raspberry_id = raspberry_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class update_farm_statusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update_farm_statusResponse", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.update_farm_statusResponseBody Body;
        
        public update_farm_statusResponse() {
        }
        
        public update_farm_statusResponse(AISCM.ServiceReference2.update_farm_statusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class update_farm_statusResponseBody {
        
        public update_farm_statusResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AISCM.ServiceReference2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AISCM.ServiceReference2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AISCM.ServiceReference2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AISCMSoapChannel : AISCM.ServiceReference2.AISCMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class signinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public signinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class signupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public signupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class adduserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public adduserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class get_current_farm_statusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public get_current_farm_statusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AISCMSoapClient : System.ServiceModel.ClientBase<AISCM.ServiceReference2.AISCMSoap>, AISCM.ServiceReference2.AISCMSoap {
        
        private BeginOperationDelegate onBeginsigninDelegate;
        
        private EndOperationDelegate onEndsigninDelegate;
        
        private System.Threading.SendOrPostCallback onsigninCompletedDelegate;
        
        private BeginOperationDelegate onBeginsignupDelegate;
        
        private EndOperationDelegate onEndsignupDelegate;
        
        private System.Threading.SendOrPostCallback onsignupCompletedDelegate;
        
        private BeginOperationDelegate onBeginadduserDelegate;
        
        private EndOperationDelegate onEndadduserDelegate;
        
        private System.Threading.SendOrPostCallback onadduserCompletedDelegate;
        
        private BeginOperationDelegate onBeginget_current_farm_statusDelegate;
        
        private EndOperationDelegate onEndget_current_farm_statusDelegate;
        
        private System.Threading.SendOrPostCallback onget_current_farm_statusCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdate_farm_statusDelegate;
        
        private EndOperationDelegate onEndupdate_farm_statusDelegate;
        
        private System.Threading.SendOrPostCallback onupdate_farm_statusCompletedDelegate;
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AISCMSoapClient() : 
                base(AISCMSoapClient.GetDefaultBinding(), AISCMSoapClient.GetDefaultEndpointAddress()) {
        }
        
        public AISCMSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AISCMSoapClient.GetBindingForEndpoint(endpointConfiguration), AISCMSoapClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public AISCMSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AISCMSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public AISCMSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AISCMSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public AISCMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<signinCompletedEventArgs> signinCompleted;
        
        public event System.EventHandler<signupCompletedEventArgs> signupCompleted;
        
        public event System.EventHandler<adduserCompletedEventArgs> adduserCompleted;
        
        public event System.EventHandler<get_current_farm_statusCompletedEventArgs> get_current_farm_statusCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> update_farm_statusCompleted;
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AISCM.ServiceReference2.AISCMSoap.Beginsignin(AISCM.ServiceReference2.signinRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsignin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginsignin(string email, System.AsyncCallback callback, object asyncState) {
            AISCM.ServiceReference2.signinRequest inValue = new AISCM.ServiceReference2.signinRequest();
            inValue.Body = new AISCM.ServiceReference2.signinRequestBody();
            inValue.Body.email = email;
            return ((AISCM.ServiceReference2.AISCMSoap)(this)).Beginsignin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AISCM.ServiceReference2.signinResponse AISCM.ServiceReference2.AISCMSoap.Endsignin(System.IAsyncResult result) {
            return base.Channel.Endsignin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private int Endsignin(System.IAsyncResult result) {
            AISCM.ServiceReference2.signinResponse retVal = ((AISCM.ServiceReference2.AISCMSoap)(this)).Endsignin(result);
            return retVal.Body.signinResult;
        }
        
        private System.IAsyncResult OnBeginsignin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            return this.Beginsignin(email, callback, asyncState);
        }
        
        private object[] OnEndsignin(System.IAsyncResult result) {
            int retVal = this.Endsignin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsigninCompleted(object state) {
            if ((this.signinCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.signinCompleted(this, new signinCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void signinAsync(string email) {
            this.signinAsync(email, null);
        }
        
        public void signinAsync(string email, object userState) {
            if ((this.onBeginsigninDelegate == null)) {
                this.onBeginsigninDelegate = new BeginOperationDelegate(this.OnBeginsignin);
            }
            if ((this.onEndsigninDelegate == null)) {
                this.onEndsigninDelegate = new EndOperationDelegate(this.OnEndsignin);
            }
            if ((this.onsigninCompletedDelegate == null)) {
                this.onsigninCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsigninCompleted);
            }
            base.InvokeAsync(this.onBeginsigninDelegate, new object[] {
                        email}, this.onEndsigninDelegate, this.onsigninCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AISCM.ServiceReference2.AISCMSoap.Beginsignup(AISCM.ServiceReference2.signupRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsignup(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginsignup(string email, string name, string gender, System.AsyncCallback callback, object asyncState) {
            AISCM.ServiceReference2.signupRequest inValue = new AISCM.ServiceReference2.signupRequest();
            inValue.Body = new AISCM.ServiceReference2.signupRequestBody();
            inValue.Body.email = email;
            inValue.Body.name = name;
            inValue.Body.gender = gender;
            return ((AISCM.ServiceReference2.AISCMSoap)(this)).Beginsignup(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AISCM.ServiceReference2.signupResponse AISCM.ServiceReference2.AISCMSoap.Endsignup(System.IAsyncResult result) {
            return base.Channel.Endsignup(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private int Endsignup(System.IAsyncResult result) {
            AISCM.ServiceReference2.signupResponse retVal = ((AISCM.ServiceReference2.AISCMSoap)(this)).Endsignup(result);
            return retVal.Body.signupResult;
        }
        
        private System.IAsyncResult OnBeginsignup(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string name = ((string)(inValues[1]));
            string gender = ((string)(inValues[2]));
            return this.Beginsignup(email, name, gender, callback, asyncState);
        }
        
        private object[] OnEndsignup(System.IAsyncResult result) {
            int retVal = this.Endsignup(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsignupCompleted(object state) {
            if ((this.signupCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.signupCompleted(this, new signupCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void signupAsync(string email, string name, string gender) {
            this.signupAsync(email, name, gender, null);
        }
        
        public void signupAsync(string email, string name, string gender, object userState) {
            if ((this.onBeginsignupDelegate == null)) {
                this.onBeginsignupDelegate = new BeginOperationDelegate(this.OnBeginsignup);
            }
            if ((this.onEndsignupDelegate == null)) {
                this.onEndsignupDelegate = new EndOperationDelegate(this.OnEndsignup);
            }
            if ((this.onsignupCompletedDelegate == null)) {
                this.onsignupCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsignupCompleted);
            }
            base.InvokeAsync(this.onBeginsignupDelegate, new object[] {
                        email,
                        name,
                        gender}, this.onEndsignupDelegate, this.onsignupCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AISCM.ServiceReference2.AISCMSoap.Beginadduser(AISCM.ServiceReference2.adduserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginadduser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginadduser(string email, string user_type, string raspberry_id, System.AsyncCallback callback, object asyncState) {
            AISCM.ServiceReference2.adduserRequest inValue = new AISCM.ServiceReference2.adduserRequest();
            inValue.Body = new AISCM.ServiceReference2.adduserRequestBody();
            inValue.Body.email = email;
            inValue.Body.user_type = user_type;
            inValue.Body.raspberry_id = raspberry_id;
            return ((AISCM.ServiceReference2.AISCMSoap)(this)).Beginadduser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AISCM.ServiceReference2.adduserResponse AISCM.ServiceReference2.AISCMSoap.Endadduser(System.IAsyncResult result) {
            return base.Channel.Endadduser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string Endadduser(System.IAsyncResult result) {
            AISCM.ServiceReference2.adduserResponse retVal = ((AISCM.ServiceReference2.AISCMSoap)(this)).Endadduser(result);
            return retVal.Body.adduserResult;
        }
        
        private System.IAsyncResult OnBeginadduser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string user_type = ((string)(inValues[1]));
            string raspberry_id = ((string)(inValues[2]));
            return this.Beginadduser(email, user_type, raspberry_id, callback, asyncState);
        }
        
        private object[] OnEndadduser(System.IAsyncResult result) {
            string retVal = this.Endadduser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnadduserCompleted(object state) {
            if ((this.adduserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.adduserCompleted(this, new adduserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void adduserAsync(string email, string user_type, string raspberry_id) {
            this.adduserAsync(email, user_type, raspberry_id, null);
        }
        
        public void adduserAsync(string email, string user_type, string raspberry_id, object userState) {
            if ((this.onBeginadduserDelegate == null)) {
                this.onBeginadduserDelegate = new BeginOperationDelegate(this.OnBeginadduser);
            }
            if ((this.onEndadduserDelegate == null)) {
                this.onEndadduserDelegate = new EndOperationDelegate(this.OnEndadduser);
            }
            if ((this.onadduserCompletedDelegate == null)) {
                this.onadduserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnadduserCompleted);
            }
            base.InvokeAsync(this.onBeginadduserDelegate, new object[] {
                        email,
                        user_type,
                        raspberry_id}, this.onEndadduserDelegate, this.onadduserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AISCM.ServiceReference2.AISCMSoap.Beginget_current_farm_status(AISCM.ServiceReference2.get_current_farm_statusRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginget_current_farm_status(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginget_current_farm_status(string email, System.AsyncCallback callback, object asyncState) {
            AISCM.ServiceReference2.get_current_farm_statusRequest inValue = new AISCM.ServiceReference2.get_current_farm_statusRequest();
            inValue.Body = new AISCM.ServiceReference2.get_current_farm_statusRequestBody();
            inValue.Body.email = email;
            return ((AISCM.ServiceReference2.AISCMSoap)(this)).Beginget_current_farm_status(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AISCM.ServiceReference2.get_current_farm_statusResponse AISCM.ServiceReference2.AISCMSoap.Endget_current_farm_status(System.IAsyncResult result) {
            return base.Channel.Endget_current_farm_status(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string Endget_current_farm_status(System.IAsyncResult result) {
            AISCM.ServiceReference2.get_current_farm_statusResponse retVal = ((AISCM.ServiceReference2.AISCMSoap)(this)).Endget_current_farm_status(result);
            return retVal.Body.get_current_farm_statusResult;
        }
        
        private System.IAsyncResult OnBeginget_current_farm_status(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            return this.Beginget_current_farm_status(email, callback, asyncState);
        }
        
        private object[] OnEndget_current_farm_status(System.IAsyncResult result) {
            string retVal = this.Endget_current_farm_status(result);
            return new object[] {
                    retVal};
        }
        
        private void Onget_current_farm_statusCompleted(object state) {
            if ((this.get_current_farm_statusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.get_current_farm_statusCompleted(this, new get_current_farm_statusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void get_current_farm_statusAsync(string email) {
            this.get_current_farm_statusAsync(email, null);
        }
        
        public void get_current_farm_statusAsync(string email, object userState) {
            if ((this.onBeginget_current_farm_statusDelegate == null)) {
                this.onBeginget_current_farm_statusDelegate = new BeginOperationDelegate(this.OnBeginget_current_farm_status);
            }
            if ((this.onEndget_current_farm_statusDelegate == null)) {
                this.onEndget_current_farm_statusDelegate = new EndOperationDelegate(this.OnEndget_current_farm_status);
            }
            if ((this.onget_current_farm_statusCompletedDelegate == null)) {
                this.onget_current_farm_statusCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onget_current_farm_statusCompleted);
            }
            base.InvokeAsync(this.onBeginget_current_farm_statusDelegate, new object[] {
                        email}, this.onEndget_current_farm_statusDelegate, this.onget_current_farm_statusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AISCM.ServiceReference2.AISCMSoap.Beginupdate_farm_status(AISCM.ServiceReference2.update_farm_statusRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginupdate_farm_status(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginupdate_farm_status(string temp, string moisture, string raspberry_id, System.AsyncCallback callback, object asyncState) {
            AISCM.ServiceReference2.update_farm_statusRequest inValue = new AISCM.ServiceReference2.update_farm_statusRequest();
            inValue.Body = new AISCM.ServiceReference2.update_farm_statusRequestBody();
            inValue.Body.temp = temp;
            inValue.Body.moisture = moisture;
            inValue.Body.raspberry_id = raspberry_id;
            return ((AISCM.ServiceReference2.AISCMSoap)(this)).Beginupdate_farm_status(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AISCM.ServiceReference2.update_farm_statusResponse AISCM.ServiceReference2.AISCMSoap.Endupdate_farm_status(System.IAsyncResult result) {
            return base.Channel.Endupdate_farm_status(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void Endupdate_farm_status(System.IAsyncResult result) {
            AISCM.ServiceReference2.update_farm_statusResponse retVal = ((AISCM.ServiceReference2.AISCMSoap)(this)).Endupdate_farm_status(result);
        }
        
        private System.IAsyncResult OnBeginupdate_farm_status(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string temp = ((string)(inValues[0]));
            string moisture = ((string)(inValues[1]));
            string raspberry_id = ((string)(inValues[2]));
            return this.Beginupdate_farm_status(temp, moisture, raspberry_id, callback, asyncState);
        }
        
        private object[] OnEndupdate_farm_status(System.IAsyncResult result) {
            this.Endupdate_farm_status(result);
            return null;
        }
        
        private void Onupdate_farm_statusCompleted(object state) {
            if ((this.update_farm_statusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.update_farm_statusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void update_farm_statusAsync(string temp, string moisture, string raspberry_id) {
            this.update_farm_statusAsync(temp, moisture, raspberry_id, null);
        }
        
        public void update_farm_statusAsync(string temp, string moisture, string raspberry_id, object userState) {
            if ((this.onBeginupdate_farm_statusDelegate == null)) {
                this.onBeginupdate_farm_statusDelegate = new BeginOperationDelegate(this.OnBeginupdate_farm_status);
            }
            if ((this.onEndupdate_farm_statusDelegate == null)) {
                this.onEndupdate_farm_statusDelegate = new EndOperationDelegate(this.OnEndupdate_farm_status);
            }
            if ((this.onupdate_farm_statusCompletedDelegate == null)) {
                this.onupdate_farm_statusCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onupdate_farm_statusCompleted);
            }
            base.InvokeAsync(this.onBeginupdate_farm_statusDelegate, new object[] {
                        temp,
                        moisture,
                        raspberry_id}, this.onEndupdate_farm_statusDelegate, this.onupdate_farm_statusCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AISCM.ServiceReference2.AISCMSoap.BeginHelloWorld(AISCM.ServiceReference2.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            AISCM.ServiceReference2.HelloWorldRequest inValue = new AISCM.ServiceReference2.HelloWorldRequest();
            inValue.Body = new AISCM.ServiceReference2.HelloWorldRequestBody();
            return ((AISCM.ServiceReference2.AISCMSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AISCM.ServiceReference2.HelloWorldResponse AISCM.ServiceReference2.AISCMSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloWorld(System.IAsyncResult result) {
            AISCM.ServiceReference2.HelloWorldResponse retVal = ((AISCM.ServiceReference2.AISCMSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AISCM.ServiceReference2.AISCMSoap CreateChannel() {
            return new AISCMSoapClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.AISCMSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.AISCMSoap)) {
                return new System.ServiceModel.EndpointAddress("http://agc2017.azurewebsites.net/AISCM.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return AISCMSoapClient.GetBindingForEndpoint(EndpointConfiguration.AISCMSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return AISCMSoapClient.GetEndpointAddress(EndpointConfiguration.AISCMSoap);
        }
        
        private class AISCMSoapClientChannel : ChannelBase<AISCM.ServiceReference2.AISCMSoap>, AISCM.ServiceReference2.AISCMSoap {
            
            public AISCMSoapClientChannel(System.ServiceModel.ClientBase<AISCM.ServiceReference2.AISCMSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult Beginsignin(AISCM.ServiceReference2.signinRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("signin", _args, callback, asyncState);
                return _result;
            }
            
            public AISCM.ServiceReference2.signinResponse Endsignin(System.IAsyncResult result) {
                object[] _args = new object[0];
                AISCM.ServiceReference2.signinResponse _result = ((AISCM.ServiceReference2.signinResponse)(base.EndInvoke("signin", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginsignup(AISCM.ServiceReference2.signupRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("signup", _args, callback, asyncState);
                return _result;
            }
            
            public AISCM.ServiceReference2.signupResponse Endsignup(System.IAsyncResult result) {
                object[] _args = new object[0];
                AISCM.ServiceReference2.signupResponse _result = ((AISCM.ServiceReference2.signupResponse)(base.EndInvoke("signup", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginadduser(AISCM.ServiceReference2.adduserRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("adduser", _args, callback, asyncState);
                return _result;
            }
            
            public AISCM.ServiceReference2.adduserResponse Endadduser(System.IAsyncResult result) {
                object[] _args = new object[0];
                AISCM.ServiceReference2.adduserResponse _result = ((AISCM.ServiceReference2.adduserResponse)(base.EndInvoke("adduser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginget_current_farm_status(AISCM.ServiceReference2.get_current_farm_statusRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("get_current_farm_status", _args, callback, asyncState);
                return _result;
            }
            
            public AISCM.ServiceReference2.get_current_farm_statusResponse Endget_current_farm_status(System.IAsyncResult result) {
                object[] _args = new object[0];
                AISCM.ServiceReference2.get_current_farm_statusResponse _result = ((AISCM.ServiceReference2.get_current_farm_statusResponse)(base.EndInvoke("get_current_farm_status", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginupdate_farm_status(AISCM.ServiceReference2.update_farm_statusRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("update_farm_status", _args, callback, asyncState);
                return _result;
            }
            
            public AISCM.ServiceReference2.update_farm_statusResponse Endupdate_farm_status(System.IAsyncResult result) {
                object[] _args = new object[0];
                AISCM.ServiceReference2.update_farm_statusResponse _result = ((AISCM.ServiceReference2.update_farm_statusResponse)(base.EndInvoke("update_farm_status", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginHelloWorld(AISCM.ServiceReference2.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public AISCM.ServiceReference2.HelloWorldResponse EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                AISCM.ServiceReference2.HelloWorldResponse _result = ((AISCM.ServiceReference2.HelloWorldResponse)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            AISCMSoap,
        }
    }
}
