//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AISCM.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AISCM.Resources.AppResource", typeof(AppResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana.
        /// </summary>
        internal static string banana {
            get {
                return ResourceManager.GetString("banana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Marketing.
        /// </summary>
        internal static string CropMarketing {
            get {
                return ResourceManager.GetString("CropMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertilizers Suggested.
        /// </summary>
        internal static string FertilizersSuggested {
            get {
                return ResourceManager.GetString("FertilizersSuggested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groundnut.
        /// </summary>
        internal static string groundnut {
            get {
                return ResourceManager.GetString("groundnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackfruit.
        /// </summary>
        internal static string jackfruit {
            get {
                return ResourceManager.GetString("jackfruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mango.
        /// </summary>
        internal static string mango {
            get {
                return ResourceManager.GetString("mango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Status Of Farm.
        /// </summary>
        internal static string MonitorStatusOfFarm {
            get {
                return ResourceManager.GetString("MonitorStatusOfFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moong.
        /// </summary>
        internal static string moong {
            get {
                return ResourceManager.GetString("moong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rice.
        /// </summary>
        internal static string Rice {
            get {
                return ResourceManager.GetString("Rice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Crop.
        /// </summary>
        internal static string SelectCrop {
            get {
                return ResourceManager.GetString("SelectCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank Status.
        /// </summary>
        internal static string TankStatus {
            get {
                return ResourceManager.GetString("TankStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udid.
        /// </summary>
        internal static string udid {
            get {
                return ResourceManager.GetString("udid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Selected Crops.
        /// </summary>
        internal static string ViewSelectedCrops {
            get {
                return ResourceManager.GetString("ViewSelectedCrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To My APP!!!.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
